/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Igor Lamoia Queiroz
 */
public class MipsSimulator extends javax.swing.JFrame {

    /**
     * Creates new form MipsSimulator
     */
    private List<String> Linhas = new ArrayList<>();
    private String console = "";

    public MipsSimulator(List<String> Linhas) {
        initComponents();
        this.Linhas = Linhas;
        this.jTextS0.setText("testando sapoha");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_clock_down = new javax.swing.JButton();
        jPanelInterfaceRegis = new javax.swing.JPanel();
        jButton_clock_up = new javax.swing.JButton();
        jTextLinhaLida = new javax.swing.JTextField();
        jPanelRegistradores = new javax.swing.JPanel();
        jTextS1 = new javax.swing.JTextField();
        jTextS2 = new javax.swing.JTextField();
        jTextS3 = new javax.swing.JTextField();
        jTextS4 = new javax.swing.JTextField();
        jTextS5 = new javax.swing.JTextField();
        jTextS6 = new javax.swing.JTextField();
        jTextS7 = new javax.swing.JTextField();
        jTextS0 = new javax.swing.JTextField();
        jTextValueS0 = new javax.swing.JTextField();
        jTextValueS1 = new javax.swing.JTextField();
        jTextValueS2 = new javax.swing.JTextField();
        jTextValueS3 = new javax.swing.JTextField();
        jTextValueS4 = new javax.swing.JTextField();
        jTextValueS5 = new javax.swing.JTextField();
        jTextValueS7 = new javax.swing.JTextField();
        jTextValueS6 = new javax.swing.JTextField();
        jTextValueT8 = new javax.swing.JTextField();
        jTextValueT9 = new javax.swing.JTextField();
        jTextT8 = new javax.swing.JTextField();
        jTextT9 = new javax.swing.JTextField();
        jLabelNomeRegistrador = new javax.swing.JLabel();
        jLabelValorRegistrador = new javax.swing.JLabel();
        jTextNomeS0 = new javax.swing.JTextField();
        jTextNomeS1 = new javax.swing.JTextField();
        jTextNomeS2 = new javax.swing.JTextField();
        jTextNomeS3 = new javax.swing.JTextField();
        jTextNomeS4 = new javax.swing.JTextField();
        jTextNomeS5 = new javax.swing.JTextField();
        jTextNomeS6 = new javax.swing.JTextField();
        jTextNomeS7 = new javax.swing.JTextField();
        jTextNomeS8 = new javax.swing.JTextField();
        jTextNomeS9 = new javax.swing.JTextField();
        jTextNomeT0 = new javax.swing.JTextField();
        jTextValueT0 = new javax.swing.JTextField();
        jTextT0 = new javax.swing.JTextField();
        jTextT1 = new javax.swing.JTextField();
        jTextValueT1 = new javax.swing.JTextField();
        jTextNomeT1 = new javax.swing.JTextField();
        jTextNomeT2 = new javax.swing.JTextField();
        jTextT2 = new javax.swing.JTextField();
        jTextValueT2 = new javax.swing.JTextField();
        jTextNomeT3 = new javax.swing.JTextField();
        jTextT3 = new javax.swing.JTextField();
        jTextValueT3 = new javax.swing.JTextField();
        jTextT4 = new javax.swing.JTextField();
        jTextValueT4 = new javax.swing.JTextField();
        jTextNomeT4 = new javax.swing.JTextField();
        jTextNomeT5 = new javax.swing.JTextField();
        jTextValueT5 = new javax.swing.JTextField();
        jTextT5 = new javax.swing.JTextField();
        jTextValueT6 = new javax.swing.JTextField();
        jTextNomeT6 = new javax.swing.JTextField();
        jTextT6 = new javax.swing.JTextField();
        jTextNomeT7 = new javax.swing.JTextField();
        jTextValueT7 = new javax.swing.JTextField();
        jTextT7 = new javax.swing.JTextField();
        jLabelNumeroRegistrador = new javax.swing.JLabel();
        jTextNomeZero = new javax.swing.JTextField();
        jTextValueZero = new javax.swing.JTextField();
        jTextZero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jButton_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DaddyTimeMono NF", 3, 48)); // NOI18N
        jLabel1.setText("Simulador Mips");

        jButton_clock_down.setFont(new java.awt.Font("JetBrains Mono", 1, 11)); // NOI18N
        jButton_clock_down.setText("Descer Clock ");
        jButton_clock_down.setActionCommand("jButton_clock_down");
        jButton_clock_down.setBorder(null);
        jButton_clock_down.setBorderPainted(false);
        jButton_clock_down.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_clock_down.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_clock_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clock_downAction(evt);
            }
        });

        javax.swing.GroupLayout jPanelInterfaceRegisLayout = new javax.swing.GroupLayout(jPanelInterfaceRegis);
        jPanelInterfaceRegis.setLayout(jPanelInterfaceRegisLayout);
        jPanelInterfaceRegisLayout.setHorizontalGroup(
            jPanelInterfaceRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelInterfaceRegisLayout.setVerticalGroup(
            jPanelInterfaceRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jButton_clock_up.setFont(new java.awt.Font("JetBrains Mono", 1, 11)); // NOI18N
        jButton_clock_up.setText("Subir Clock (ler)");
        jButton_clock_up.setActionCommand("jButton_clock_up");
        jButton_clock_up.setBorder(null);
        jButton_clock_up.setBorderPainted(false);
        jButton_clock_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_clock_up.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_clock_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clock_upAction(evt);
            }
        });

        jPanelRegistradores.setBackground(new java.awt.Color(231, 254, 254));

        jTextS1.setToolTipText("");

        jTextS2.setToolTipText("");

        jTextS3.setToolTipText("");

        jTextS4.setToolTipText("");

        jTextS5.setToolTipText("");

        jTextS6.setToolTipText("");

        jTextS7.setToolTipText("");

        jTextS0.setToolTipText("");

        jTextValueS0.setEditable(false);
        jTextValueS0.setText("16");

        jTextValueS1.setEditable(false);
        jTextValueS1.setText("17");

        jTextValueS2.setEditable(false);
        jTextValueS2.setText("18");

        jTextValueS3.setEditable(false);
        jTextValueS3.setText("19");

        jTextValueS4.setEditable(false);
        jTextValueS4.setText("20");

        jTextValueS5.setEditable(false);
        jTextValueS5.setText("21");

        jTextValueS7.setEditable(false);
        jTextValueS7.setText("23");

        jTextValueS6.setEditable(false);
        jTextValueS6.setText("22");
        jTextValueS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValueS6ActionPerformed(evt);
            }
        });

        jTextValueT8.setEditable(false);
        jTextValueT8.setText("24");

        jTextValueT9.setEditable(false);
        jTextValueT9.setText("25");

        jTextT8.setToolTipText("");

        jTextT9.setToolTipText("");

        jLabelNomeRegistrador.setFont(new java.awt.Font("Dank Mono", 1, 14)); // NOI18N
        jLabelNomeRegistrador.setText("Nome");

        jLabelValorRegistrador.setFont(new java.awt.Font("Dank Mono", 1, 14)); // NOI18N
        jLabelValorRegistrador.setText("Valor");

        jTextNomeS0.setEditable(false);
        jTextNomeS0.setText("$S0");
        jTextNomeS0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS0ActionPerformed(evt);
            }
        });

        jTextNomeS1.setEditable(false);
        jTextNomeS1.setText("$S1");
        jTextNomeS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS1ActionPerformed(evt);
            }
        });

        jTextNomeS2.setEditable(false);
        jTextNomeS2.setText("$S2");
        jTextNomeS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS2ActionPerformed(evt);
            }
        });

        jTextNomeS3.setEditable(false);
        jTextNomeS3.setText("$S3");
        jTextNomeS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS3ActionPerformed(evt);
            }
        });

        jTextNomeS4.setEditable(false);
        jTextNomeS4.setText("$S4");
        jTextNomeS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS4ActionPerformed(evt);
            }
        });

        jTextNomeS5.setEditable(false);
        jTextNomeS5.setText("$S5");
        jTextNomeS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS5ActionPerformed(evt);
            }
        });

        jTextNomeS6.setEditable(false);
        jTextNomeS6.setText("$S6");
        jTextNomeS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS6ActionPerformed(evt);
            }
        });

        jTextNomeS7.setEditable(false);
        jTextNomeS7.setText("$S7");
        jTextNomeS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS7ActionPerformed(evt);
            }
        });

        jTextNomeS8.setEditable(false);
        jTextNomeS8.setText("$T8");
        jTextNomeS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS8ActionPerformed(evt);
            }
        });

        jTextNomeS9.setEditable(false);
        jTextNomeS9.setText("$T9");
        jTextNomeS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeS9ActionPerformed(evt);
            }
        });

        jTextNomeT0.setEditable(false);
        jTextNomeT0.setText("$T0");
        jTextNomeT0.setToolTipText("");
        jTextNomeT0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT0ActionPerformed(evt);
            }
        });

        jTextValueT0.setEditable(false);
        jTextValueT0.setText("8");

        jTextT0.setToolTipText("");

        jTextT1.setToolTipText("");

        jTextValueT1.setEditable(false);
        jTextValueT1.setText("9");

        jTextNomeT1.setEditable(false);
        jTextNomeT1.setText("$T1");
        jTextNomeT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT1ActionPerformed(evt);
            }
        });

        jTextNomeT2.setEditable(false);
        jTextNomeT2.setText("$T2");
        jTextNomeT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT2ActionPerformed(evt);
            }
        });

        jTextT2.setToolTipText("");

        jTextValueT2.setEditable(false);
        jTextValueT2.setText("10");

        jTextNomeT3.setEditable(false);
        jTextNomeT3.setText("$T3");
        jTextNomeT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT3ActionPerformed(evt);
            }
        });

        jTextT3.setToolTipText("");

        jTextValueT3.setEditable(false);
        jTextValueT3.setText("11");

        jTextT4.setToolTipText("");

        jTextValueT4.setEditable(false);
        jTextValueT4.setText("12");

        jTextNomeT4.setEditable(false);
        jTextNomeT4.setText("$T4");
        jTextNomeT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT4ActionPerformed(evt);
            }
        });

        jTextNomeT5.setEditable(false);
        jTextNomeT5.setText("$T5");
        jTextNomeT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT5ActionPerformed(evt);
            }
        });

        jTextValueT5.setEditable(false);
        jTextValueT5.setText("13");

        jTextT5.setToolTipText("");

        jTextValueT6.setEditable(false);
        jTextValueT6.setText("14");

        jTextNomeT6.setEditable(false);
        jTextNomeT6.setText("$T6");
        jTextNomeT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT6ActionPerformed(evt);
            }
        });

        jTextT6.setToolTipText("");

        jTextNomeT7.setEditable(false);
        jTextNomeT7.setText("$T7");
        jTextNomeT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeT7ActionPerformed(evt);
            }
        });

        jTextValueT7.setEditable(false);
        jTextValueT7.setText("15");

        jTextT7.setToolTipText("");

        jLabelNumeroRegistrador.setFont(new java.awt.Font("Dank Mono", 1, 14)); // NOI18N
        jLabelNumeroRegistrador.setText("Número");

        jTextNomeZero.setEditable(false);
        jTextNomeZero.setText("$zero");
        jTextNomeZero.setToolTipText("");
        jTextNomeZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeZeroActionPerformed(evt);
            }
        });

        jTextValueZero.setEditable(false);
        jTextValueZero.setText("0");

        jTextZero.setToolTipText("");

        javax.swing.GroupLayout jPanelRegistradoresLayout = new javax.swing.GroupLayout(jPanelRegistradores);
        jPanelRegistradores.setLayout(jPanelRegistradoresLayout);
        jPanelRegistradoresLayout.setHorizontalGroup(
            jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistradoresLayout.createSequentialGroup()
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNomeS0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextValueS1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueT8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueT9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistradoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextNomeT7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextValueT7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistradoresLayout.createSequentialGroup()
                                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNomeRegistrador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNomeT0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNomeZero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextValueT0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNumeroRegistrador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextValueZero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextS0)
                    .addComponent(jTextS1)
                    .addComponent(jTextS2)
                    .addComponent(jTextS3)
                    .addComponent(jTextS4)
                    .addComponent(jTextS5)
                    .addComponent(jTextS6)
                    .addComponent(jTextS7)
                    .addComponent(jTextT8)
                    .addComponent(jTextT9)
                    .addComponent(jLabelValorRegistrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextT2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextT3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextT4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextT5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextT6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextT7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextZero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT0)
                    .addComponent(jTextT1))
                .addContainerGap())
        );
        jPanelRegistradoresLayout.setVerticalGroup(
            jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeRegistrador)
                    .addComponent(jLabelValorRegistrador)
                    .addComponent(jLabelNumeroRegistrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextNomeT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValueT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextS0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValueS0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextValueS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextValueS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNomeS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextValueS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNomeS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextValueS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNomeS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextValueS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNomeS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextValueS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNomeS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextValueS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNomeS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addComponent(jTextT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextT9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradoresLayout.createSequentialGroup()
                                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextValueT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNomeS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelRegistradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextValueT9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNomeS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jTextNomeS0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsole);

        jButton_reset.setFont(new java.awt.Font("JetBrains Mono", 1, 11)); // NOI18N
        jButton_reset.setText("Resetar");
        jButton_reset.setActionCommand("jButton_reset");
        jButton_reset.setBorder(null);
        jButton_reset.setBorderPainted(false);
        jButton_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelInterfaceRegis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(550, 550, 550))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextLinhaLida, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_clock_up, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_clock_down, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRegistradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextLinhaLida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_clock_up, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_clock_down, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jPanelInterfaceRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanelRegistradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jlabel_titulo");
        jLabel1.getAccessibleContext().setAccessibleDescription("Título do Simulador");
        jButton_clock_down.getAccessibleContext().setAccessibleName("jButton_clock_down");
        jButton_clock_down.getAccessibleContext().setAccessibleDescription("Botão para descer clock  (escrever)");
        jTextLinhaLida.getAccessibleContext().setAccessibleName("Linha lida do comando");
        jButton_reset.getAccessibleContext().setAccessibleName("Limpar programa");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_clock_downAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clock_downAction
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_clock_downAction

    private void jButton_clock_upAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clock_upAction
        // TODO add your handling code here:
        for(String linha : this.jTextAreaConsole.getText().split("\n")) {
            console += linha+"\n";
        }
        System.out.println(console);
        
    
        for(String i : console.split("\n")) {
            // System.out.println(i);
        }
    }//GEN-LAST:event_jButton_clock_upAction

    private void jTextNomeS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS9ActionPerformed

    private void jTextNomeS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS8ActionPerformed

    private void jTextNomeS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS7ActionPerformed

    private void jTextNomeS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS6ActionPerformed

    private void jTextNomeS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS5ActionPerformed

    private void jTextNomeS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS4ActionPerformed

    private void jTextNomeS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS3ActionPerformed

    private void jTextNomeS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS2ActionPerformed

    private void jTextNomeS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS1ActionPerformed

    private void jTextNomeS0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeS0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeS0ActionPerformed

    private void jTextValueS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValueS6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValueS6ActionPerformed

    private void jTextNomeT0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT0ActionPerformed

    private void jTextNomeT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT1ActionPerformed

    private void jTextNomeT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT2ActionPerformed

    private void jTextNomeT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT3ActionPerformed

    private void jTextNomeT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT4ActionPerformed

    private void jTextNomeT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT5ActionPerformed

    private void jTextNomeT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT6ActionPerformed

    private void jTextNomeT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeT7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeT7ActionPerformed

    private void jTextNomeZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeZeroActionPerformed

    private void jButton_resetAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetAction
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_resetAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MipsSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MipsSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MipsSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MipsSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new MipsSimulator().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clock_down;
    private javax.swing.JButton jButton_clock_up;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeRegistrador;
    private javax.swing.JLabel jLabelNumeroRegistrador;
    private javax.swing.JLabel jLabelValorRegistrador;
    private javax.swing.JPanel jPanelInterfaceRegis;
    private javax.swing.JPanel jPanelRegistradores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JTextField jTextLinhaLida;
    private javax.swing.JTextField jTextNomeS0;
    private javax.swing.JTextField jTextNomeS1;
    private javax.swing.JTextField jTextNomeS2;
    private javax.swing.JTextField jTextNomeS3;
    private javax.swing.JTextField jTextNomeS4;
    private javax.swing.JTextField jTextNomeS5;
    private javax.swing.JTextField jTextNomeS6;
    private javax.swing.JTextField jTextNomeS7;
    private javax.swing.JTextField jTextNomeS8;
    private javax.swing.JTextField jTextNomeS9;
    private javax.swing.JTextField jTextNomeT0;
    private javax.swing.JTextField jTextNomeT1;
    private javax.swing.JTextField jTextNomeT2;
    private javax.swing.JTextField jTextNomeT3;
    private javax.swing.JTextField jTextNomeT4;
    private javax.swing.JTextField jTextNomeT5;
    private javax.swing.JTextField jTextNomeT6;
    private javax.swing.JTextField jTextNomeT7;
    private javax.swing.JTextField jTextNomeZero;
    private javax.swing.JTextField jTextS0;
    private javax.swing.JTextField jTextS1;
    private javax.swing.JTextField jTextS2;
    private javax.swing.JTextField jTextS3;
    private javax.swing.JTextField jTextS4;
    private javax.swing.JTextField jTextS5;
    private javax.swing.JTextField jTextS6;
    private javax.swing.JTextField jTextS7;
    private javax.swing.JTextField jTextT0;
    private javax.swing.JTextField jTextT1;
    private javax.swing.JTextField jTextT2;
    private javax.swing.JTextField jTextT3;
    private javax.swing.JTextField jTextT4;
    private javax.swing.JTextField jTextT5;
    private javax.swing.JTextField jTextT6;
    private javax.swing.JTextField jTextT7;
    private javax.swing.JTextField jTextT8;
    private javax.swing.JTextField jTextT9;
    private javax.swing.JTextField jTextValueS0;
    private javax.swing.JTextField jTextValueS1;
    private javax.swing.JTextField jTextValueS2;
    private javax.swing.JTextField jTextValueS3;
    private javax.swing.JTextField jTextValueS4;
    private javax.swing.JTextField jTextValueS5;
    private javax.swing.JTextField jTextValueS6;
    private javax.swing.JTextField jTextValueS7;
    private javax.swing.JTextField jTextValueT0;
    private javax.swing.JTextField jTextValueT1;
    private javax.swing.JTextField jTextValueT2;
    private javax.swing.JTextField jTextValueT3;
    private javax.swing.JTextField jTextValueT4;
    private javax.swing.JTextField jTextValueT5;
    private javax.swing.JTextField jTextValueT6;
    private javax.swing.JTextField jTextValueT7;
    private javax.swing.JTextField jTextValueT8;
    private javax.swing.JTextField jTextValueT9;
    private javax.swing.JTextField jTextValueZero;
    private javax.swing.JTextField jTextZero;
    // End of variables declaration//GEN-END:variables
}
